#!/bin/bash

if [[ "$#" -eq 1 ]]; then
  ZMK_CONTAINER_ID="$1"
fi
if [[ -n "$ZMK_CONTAINER_ID" && "$ZMK_CONTAINER_ID" != "null" ]]; then
  docker exec -w /workspaces/zmk/app "$ZMK_CONTAINER_ID" /bin/bash -c 'west build -p -d build/left -b nice_nano_v2 -- -DSHIELD="corne_left;nice_view_adapter;nice_view" -DZMK_CONFIG="/workspaces/zmk-config/config" -DZMK_EXTRA_MODULES="/workspaces/zmk-config;/workspaces/zmk-modules/zmk-helpers"'
  docker exec -w /workspaces/zmk/app "$ZMK_CONTAINER_ID" /bin/bash -c 'west build -p -d build/right -b nice_nano_v2 -- -DSHIELD="corne_right;nice_view_adapter;nice_view" -DZMK_CONFIG="/workspaces/zmk-config/config" -DZMK_EXTRA_MODULES="/workspaces/zmk-config;/workspaces/zmk-modules/zmk-helpers"'
else
  echo "failed to run command"
  exit 1
fi
